---

- name: td-agent | get GPG key
  shell: curl https://packages.treasuredata.com/GPG-KEY-td-agent | apt-key add -

- name: td-agent | add treasure data repository to apt
  apt_repository: repo='deb http://packages.treasuredata.com/2/ubuntu/trusty/  trusty contrib' state='present'
  register: td-agent_repo

- name: td-agent | update sources
  apt: update_cache='yes'
  when: td-agent_repo | changed

- name: td-agent | install package
  apt: name='td-agent' state='present' update_cache='yes' cache_valid_time='3600'

- name: td-agent | overlay default config
  template: src='td-agent.conf.j2' dest='/etc/td-agent/td-agent.conf'

- name: td-agent | restart service and enable at boot
  service: name='td-agent' state='restarted' enabled='yes'
