---

- name: td-agent | install using curl
  shell: curl -L http://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh | sh

- name: td-agent | overlay default config
  template: src='td-agent.conf.j2' dest='/etc/td-agent/td-agent.conf'

- name: td-agent | restart service and enable at boot
  service: name='td-agent' state='restarted' enabled='yes'
